apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  description: simple hello-world application
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: msantoshnetha
  system: podcast
