name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_IMAGE_REPO: ${{ github.repository }}
      CONTAINER_REGISTRY: ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $CONTAINER_REGISTRY/$GITHUB_IMAGE_REPO/my-app:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: msantoshnetha
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: auto
          logout: true

      - name: Push Docker image to GitHub Container Registry
        run: docker push $CONTAINER_REGISTRY/$GITHUB_IMAGE_REPO/my-app:latest
